### ISSUE TITLE
Negative temperature readings

### ISSUE THREAD

**Issue by gerd289** [rosswarren/epevermodbus#11]
If any temperature (e.g. batterie temp.) drops below 0.0°C it is shown as 654.xx.

**Comment by na7q** [comment]
> If any temperature (e.g. batterie temp.) drops below 0.0°C it is shown as 654.xx.

At least on my controllers, it starts at 655.35 when dropping below 0. I just created an if statement in the script and subtracted 655.35 from it. Works like a charm it seems.

**Comment by rosswarren** [comment]
Thanks for reporting, this should be fixed in the latest version

**Comment by gerd289** [comment]
Thanks for fixing. I will give it a try within a few days.
 
 
Von: Ross Warren ***@***.*** 
Gesendet: Montag, 2. Januar 2023 14:53
An: rosswarren/epevermodbus ***@***.***>
Cc: gerd289 ***@***.***>; Author ***@***.***>
Betreff: Re: [rosswarren/epevermodbus] Negative temperature readings (Issue #11)
 
Thanks for reporting, this should be fixed in the latest version
